dist: trusty
sudo: required
language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
deploy:
  provider: heroku
  app:
    master: brainst0rm
    dev: bubblerise
  api_key:
    master:
      secure: Owuf6IVXmQCrXb7LHSJYk9sMriwc5bGxt54/c6+okt2Tz/6dehrW5F71TfCSBFb8K7na/xFRRKC7hcDamOIFs/FUk3h1rCalLgRFyM1xDllG5SUY20qhLvSF974mgLOiqX/izP4ZOxiaqwuszkuzCJ8icj0ycW8hyaUH3m8mbMskvbaFnOmTbigzqaJ6HQy3sJQ/PXf6ubT9zypAbAL/3/V+PjyttYou1D4Zm9kPS5cPeSWzVFda7vHHyUpwBX47hNFZzO39yOcH4maKxtpulb9nUrdF1RWYcJomhBUqcyVo+Cv9G2VhuT2P40NbOOtBhV9F5IvJyCpHFj1WnZV/XffkpIyk7OfLvBbhhUPxFXxZHd1YBBI06mkUbEU31D0DXGnyvXJozkikeYp6DNWoo1PqQKwd3TXaG3y7DGh1JxcTiCcitdLZJXrVJb8Vcm1asZPdh8wikQxGxenEqWOt7R3bODnSSbr7molmWr94rNk7hpkvF5rXAqOyfjy1DzdbnSKlGhYTL2Py9fP4fTydSpe3AUcSIszkTtW1T4oESQ23KlnNZF55u1b+6y2Sjb8L7UyP8xjFvu7zgM0eH4vtEAWlU+Of/3b4Zb6QDlooYWak6ma+sb0vFKKA+TiXqwcKsxq368OUYxJeVyK0K9yMSwTRlqaXe7qbfSgFRRnJ5dk=
    dev:
      secure: HpMJN8TeKKXN/b4FMlfj/9UQnEkoy3kFB7ILKqtZNbybBJiIWDSFkX21ik8vLUTY9nVi9CEPbe/p1TwPOlerVx0VlGPsNv4gEc0DlaspGJUkIanFrgVECvK1I18FG1R3bpgmsWiGuArydSomrasfI/oAgpOP1igL3/3AEwEh6RARjaqqWs5IHY3l7AFWiRHn6hlQpaoqfGVtf5qICmNwgrA4Z8riOgQ4GwgFEriCu+oo5hjzkQyJ0EwjZIDSSmgnCdSnhVWaBni7UH2+OwnXvVKeajgxZD3+ciGiVt8i2pBDUqBTPgIoDwi6n00z5/wLPNkZKXKqi2r7nYX/UykBkU6qlO2Dn9EkMsBoonZjnSkq2DgdOkNZnED5C2/45V4gim3VAPJd6tk4LA0PbXj+XOfykhVppRZy2tXgC1HcFd+emqIHAFg+zlaEPYk/+bz6PI9lyId0S9yy7NuWChldMut5EKQ8a92FhwKdS3iGPpA6vEC7bWQs/1baolacAW7pIbIlsxfyo+3gG0NxYexoy7ElsHa6NgUAm4NFWnHfLzXxMjC3OeucPLy2cgaXAfgLUUVSPTuJU/duxyndvkioLlBLIJWZDRXH+lgTDJ3q1+BWTpghaXQAdbBG5TicwlK3iZy+bCQSc3/K0r3HmBqPO3NqF8AFsTR6J0b+5aTLj0E=
script:
- echo "Hello World!"
